### ISSUE TITLE
Compatibility problem with Symfony 5 / 6

### ISSUE THREAD

**Issue by luka-jukic** [BlackbitDigitalCommerce/pimcore-data-director-bmecat#1]
Since the BMEcat export is an add-on for the Data Director, and this is already compatible with Symfony 5/6, the add-on should actually also be adapted. 

For example, the Configuration.php should be adapted. The same solution as in the DataDirector could be used here.

**Comment by BlackbitDevs** [comment]
Thanks for notifying. Is fixed in 1.2.8.
