### ISSUE TITLE
BMEcat 2005.1 Export Error while executing result callback function: Error: Class "Naugrim\BMEcat\DocumentBuilder" not found 

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director-bmecat#2]
If i run the bme cat export i get the error, that the class Naugrim\BMEcat\DocumentBuilder is not found. The class is used in the template
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/acb898da-ab36-4194-9ce0-5ea73bbea35b)
And also one class extends from it
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/3048d735-8f8c-4d62-b1b4-e600006ea22b)
Bit the class is missing in Fallback folder.
Can you please check it?
i'm using last pimcore version and v1.4.4 version of the bundle, which is also last version.
Thank you!

**Comment by ascheider** [comment]
@BlackbitDevs I know you are busy with all the issues. Any chance to add the missing class soon? It blocks me currently with my export tasks. Thank you!

**Comment by BlackbitDevs** [comment]
Which version of `naugrim/bmecat` do you have? You see this by executing `composer info naugrim/bmecat` or by looking in the composer.lock file. Actually the class should be available, see https://github.com/Naugrimm/bmecat/blob/master/src/DocumentBuilder.php

**Comment by ascheider** [comment]
@BlackbitDevs 

I ran the command, this is the version:

name     : naugrim/bmecat
descrip. : Allows to build BMEcat documents from PHP and converts them to xml
keywords : bmecat, document, serialization, xml
versions : * 0.1.4
type     : library

if i take i look into vendor folder of naugrim, there is DocumentBuilder class, but with SE\Component\BMEcat Namespace

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/ae0ec55e-f732-41eb-b2d2-86557ae9f9e6)

**Comment by BlackbitDevs** [comment]
Please run `composer update blackbit/data-director-bmecat --with-dependencies` - actually `naugrim/bmecat` should get updated to 1.0.0.

**Comment by ascheider** [comment]
@BlackbitDevs If i run the command, nothing happens.
If i try to require composer.phar require naugrim/bmecat:1.0.0 --with-all-dependencies
If get this problem:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/fcab7bfb-e67b-48fc-b3bd-63e254a5abea)
If i run composer.phar why-not naugrim/bmecat 1.0.0
I get this explanation.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/dec1d018-849e-4880-b78d-0c6de8a87f8a)
naugrim/bmecat needs symfony/expression-language in version 5 but pimcore 11 has 6.4.0 installed.

**Comment by ascheider** [comment]
@BlackbitDevs Do you have Feedback for me? It seems the bundle is not compatible with pimcore 11?
Because Pimcore 11 has depenedency to symfony/expression-language in version 6.2 https://github.com/pimcore/pimcore/blob/v11.1.3/composer.json
We found also one more bug in the bundle in the ImportEtimController and ImportClassificationstoresCommand
The class \Pimcore\Cache\Runtime does not exists anymore in pimcore 11. It is now: \Pimcore\Cache\RuntimeCache
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director-bmecat/assets/6016485/a88b49ee-c1de-446c-994c-708434bb2646)

**Comment by BlackbitDevs** [comment]
@ascheider The problem with `\Pimcore\Cache\Runtime` is fixed in 1.4.5.

The incompatibility with `naugrim/bmecat` is being addressed in https://github.com/Naugrimm/bmecat/pull/4 - we will see if this project is still active...
Beside this, we have planned to change the BMEcat function templates anyway because currently all data is first being read into RAM and then at the very end the XML gets generated - this is a huge waste of memory. We plan to do it similarly as the generic XML export in Data Director:
- append to result XML document after every item - this will use 99% less memory
- remove libraries as they are not actively maintained anyway -> eliminates such problems as you have now with `symfony/expression-language` and simplifies adjusting the XML structure. 

We are currently looking for a client who would pay for implementation, so if you are interested, please write to help@blackbit.de

**Comment by BlackbitDevs** [comment]
@ascheider Have resolved the issue with `naugrim/bmecat` - obviously it is not maintained anymore...
I have now added the code from this library to the `Fallback` directory. Should be ok from license perspective... please give version 1.4.7 a try and give some feedback if it works now.
